In [1]:
import numpy as np
from emotion_utils import *
import matplotlib.pyplot as plt
import numpy as np
from keras.models import Model
from keras.layers import Dense, Input, Dropout, LSTM, Activation
from keras.layers.embeddings import Embedding
from keras.preprocessing import sequence
from keras.initializers import glorot_uniform


%matplotlib inline

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
X_train, Y_train = read_csv('Train_300.csv')
print(X_train,Y_train)

['i feel so enraged but helpless at the same time'
 'i said feeling a bit rebellious'
 'i woke up feeling particularly vile tried to ignore it but it got worse and worse and worse'
 'i could feel the vile moth burrowing its way into my brain seeking my brain as a means to control and enslave me just as those nasty bug things did to chekov in star trek the wrath of khan'
 'i have a pretty bad feeling the last two books will be rushed in terms of story'
 'im looking right now so desperately looking for a creative project that i feel like i have had a hand in that i need to sit and write my fucking mother fucker of a fuck fuckers fucked play before i feel satisfied doing anything else'
 'i feel sickened by and disgusted with the sins of man despite my divinity i feel sickened by and disgusted with the sins of man'
 'i hated growing up i have no good memories of a life as an innocent child only the feeling of being hated and worthlessness consume the memories'
 'when my kid brother broke m

In [3]:
X_test, Y_test = read_csv('Test_150.csv')
print(X_test)

['i feel so enraged but helpless at the same time'
 'i like super committed like to the point where i feel like i could honestly see myself marrying the person and am not a fan of casual sex or sex without 5 or any of that does your mate need to be taller than you'
 'i feel strange or will i ever notice that'
 'i could feel the poisoned hateful angry buildup leaving and it made me feel lighter'
 'i was feeling so distressed so it has been added to my notes that i should never be prescribed them again'
 'i feel you as my best man someone who moves me touches my soul and puts fire in my body'
 'i feel as though im carefree'
 'i distinctly remember saying i miss being at home on a saturday night feeling amazing happiness watching movies in some soccer shorts and messy hair with my 5 instead of having to get dressed up go out and get drunk to look and feel pretty'
 'i feel that some of you loyal pistons fans are worried about the team and winning the title again'
 'i am feeling in a naught

In [4]:
maxLen = len(max(X_train, key=len).split())

In [5]:
Y_oh_train = convert_to_one_hot(Y_train, C = 6)
Y_oh_test = convert_to_one_hot(Y_test, C = 6)
print(Y_oh_test)

[[1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0.

In [6]:
index = 150
print(X_train[index], label_to_emotion(Y_train[index]))

i noe eu jux wanna make mi smile too but inside eu feel so messy amp dunno how amp helpless :sadness:


In [7]:
index = 120
print(X_train[index], label_to_emotion(Y_train[index]))

i feel as though im carefree :joy:


In [8]:
word_to_index, index_to_word, word_to_vec_map = read_glove_vecs('glove.6B.300d.txt')

In [9]:
word = "people"
index = 298377
print("the index of", word, "in the vocabulary is", word_to_index[word])
print("the", str(index) + "th word in the vocabulary is", index_to_word[index])

the index of people in the vocabulary is 280944
the 298377th word in the vocabulary is rabbit


In [10]:
def sentences_to_indices(X, word_to_index, max_len):
 
    m = X.shape[0]                                   # number of training examples
    X_indices = np.zeros((m,max_len))
    
    for i in range(m):                               
        sentence_words = [w.lower() for w in X[i].split()]
        print(sentence_words)                 
        
        j = 0
        
       
        for w in sentence_words:
         #   if w in word_to_index :
               X_indices[i, j] = word_to_index[w]
               j = j+1 
           # else:
            #    print(w)
             #   print('word is not in the vocab')
            #j = j+1
    return X_indices

In [11]:
X1 = np.array(["women are emotional"])
X1_indices = sentences_to_indices(X1,word_to_index, max_len = 5)
print("X1 =", X1)
print("X1_indices =", X1_indices)

['women', 'are', 'emotional']
X1 = ['women are emotional']
X1_indices = [[389423.  58997. 136534.      0.      0.]]


In [12]:
def pretrained_embedding_layer(word_to_vec_map, word_to_index):
       
    vocab_len = len(word_to_index) + 1                  # adding 1 to fit Keras embedding (requirement)
    emb_dim = word_to_vec_map["cucumber"].shape[0]      # define dimensionality of your GloVe word vectors (= 50)
    
    emb_matrix = np.zeros((vocab_len,emb_dim))
    for word, index in word_to_index.items():
        emb_matrix[index, :] = word_to_vec_map[word]
    embedding_layer = Embedding(vocab_len,emb_dim, trainable=False)
    embedding_layer.build((None,))
    embedding_layer.set_weights([emb_matrix])
    
    return embedding_layer

In [13]:
embedding_layer = pretrained_embedding_layer(word_to_vec_map, word_to_index)
print("weights[0][1][3] =", embedding_layer.get_weights()[0][1][3])

Instructions for updating:
Colocations handled automatically by placer.
weights[0][1][3] = -0.080934


In [14]:
def Emotion_v1(input_shape, word_to_vec_map, word_to_index):
    sentence_indices = Input(input_shape, dtype='int32')
    embedding_layer = pretrained_embedding_layer(word_to_vec_map,word_to_index)
    embeddings = embedding_layer(sentence_indices)
    
    # Propagate the embeddings through an LSTM layer with 128-dimensional hidden state
    X = LSTM(128,return_sequences= True)(embeddings)
    # Add dropout with a probability of 0.5
    X = Dropout(0.5)(X)
    # Propagate X trough another LSTM layer with 128-dimensional hidden state
    X = LSTM(128,return_sequences= False)(X)
    # Add dropout with a probability of 0.5
    X = Dropout(0.5)(X)
    # Propagate X through a Dense layer with softmax activation to get back a batch of 6-dimensional vectors.
    X = Dense(6)(X)
    # Add a softmax activation
    X = Activation('softmax')(X)
    model = Model(inputs=sentence_indices,outputs=X)

    return model

In [15]:
model = Emotion_v1((maxLen,), word_to_vec_map, word_to_index)
model.summary()

Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 56)                0         
_________________________________________________________________
embedding_2 (Embedding)      (None, 56, 300)           120000300 
_________________________________________________________________
lstm_1 (LSTM)                (None, 56, 128)           219648    
_________________________________________________________________
dropout_1 (Dropout)          (None, 56, 128)           0         
_________________________________________________________________
lstm_2 (LSTM)                (None, 128)               131584    
_________________________________________________________________
dropout_2 (Dropout)          (None, 128)               0         
___________________________

In [16]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [17]:
X_train_indices = sentences_to_indices(X_train, word_to_index, maxLen)
Y_train_oh = convert_to_one_hot(Y_train, C = 6)

['i', 'feel', 'so', 'enraged', 'but', 'helpless', 'at', 'the', 'same', 'time']
['i', 'said', 'feeling', 'a', 'bit', 'rebellious']
['i', 'woke', 'up', 'feeling', 'particularly', 'vile', 'tried', 'to', 'ignore', 'it', 'but', 'it', 'got', 'worse', 'and', 'worse', 'and', 'worse']
['i', 'could', 'feel', 'the', 'vile', 'moth', 'burrowing', 'its', 'way', 'into', 'my', 'brain', 'seeking', 'my', 'brain', 'as', 'a', 'means', 'to', 'control', 'and', 'enslave', 'me', 'just', 'as', 'those', 'nasty', 'bug', 'things', 'did', 'to', 'chekov', 'in', 'star', 'trek', 'the', 'wrath', 'of', 'khan']
['i', 'have', 'a', 'pretty', 'bad', 'feeling', 'the', 'last', 'two', 'books', 'will', 'be', 'rushed', 'in', 'terms', 'of', 'story']
['im', 'looking', 'right', 'now', 'so', 'desperately', 'looking', 'for', 'a', 'creative', 'project', 'that', 'i', 'feel', 'like', 'i', 'have', 'had', 'a', 'hand', 'in', 'that', 'i', 'need', 'to', 'sit', 'and', 'write', 'my', 'fucking', 'mother', 'fucker', 'of', 'a', 'fuck', 'fuckers'

In [18]:
model.fit(X_train_indices, Y_train_oh, epochs =80, batch_size = 32, shuffle=True)

Instructions for updating:
Use tf.cast instead.
Epoch 1/80
300/300 [==============================] - 2s 6ms/step - loss: 1.7951 - acc: 0.1167
Epoch 2/80
300/300 [==============================] - 1s 2ms/step - loss: 1.7886 - acc: 0.1767
Epoch 3/80
300/300 [==============================] - 1s 3ms/step - loss: 1.7811 - acc: 0.1567
Epoch 4/80
300/300 [==============================] - 1s 3ms/step - loss: 1.7706 - acc: 0.2067
Epoch 5/80
300/300 [==============================] - 1s 3ms/step - loss: 1.7417 - acc: 0.2267
Epoch 6/80
300/300 [==============================] - 1s 3ms/step - loss: 1.7570 - acc: 0.2100
Epoch 7/80
300/300 [==============================] - 1s 3ms/step - loss: 1.7087 - acc: 0.2533
Epoch 8/80
300/300 [==============================] - 1s 2ms/step - loss: 1.6257 - acc: 0.2967
Epoch 9/80
300/300 [==============================] - 1s 2ms/step - loss: 1.5273 - acc: 0.3133
Epoch 10/80
300/300 [==============================] - 1s 3ms/step - loss: 1.5569 - acc: 0.3133
E

In [22]:
X_test_indices = sentences_to_indices(X_test, word_to_index, max_len = maxLen)
Y_test_oh = convert_to_one_hot(Y_test, C = 6)
loss, acc = model.evaluate(X_test_indices, Y_test_oh)
print()
print("Test accuracy = ", acc)

['i', 'feel', 'so', 'enraged', 'but', 'helpless', 'at', 'the', 'same', 'time']
['i', 'like', 'super', 'committed', 'like', 'to', 'the', 'point', 'where', 'i', 'feel', 'like', 'i', 'could', 'honestly', 'see', 'myself', 'marrying', 'the', 'person', 'and', 'am', 'not', 'a', 'fan', 'of', 'casual', 'sex', 'or', 'sex', 'without', '5', 'or', 'any', 'of', 'that', 'does', 'your', 'mate', 'need', 'to', 'be', 'taller', 'than', 'you']
['i', 'feel', 'strange', 'or', 'will', 'i', 'ever', 'notice', 'that']
['i', 'could', 'feel', 'the', 'poisoned', 'hateful', 'angry', 'buildup', 'leaving', 'and', 'it', 'made', 'me', 'feel', 'lighter']
['i', 'was', 'feeling', 'so', 'distressed', 'so', 'it', 'has', 'been', 'added', 'to', 'my', 'notes', 'that', 'i', 'should', 'never', 'be', 'prescribed', 'them', 'again']
['i', 'feel', 'you', 'as', 'my', 'best', 'man', 'someone', 'who', 'moves', 'me', 'touches', 'my', 'soul', 'and', 'puts', 'fire', 'in', 'my', 'body']
['i', 'feel', 'as', 'though', 'im', 'carefree']
['i', 

151/151 [==============================] - 0s 925us/step

Test accuracy =  0.9933774834437086


In [27]:
# mislabelled examples
C = 6
y_test_oh = np.eye(C)[Y_test.reshape(-1)]
X_test_indices = sentences_to_indices(X_test, word_to_index, maxLen)
pred = model.predict(X_test_indices)
for i in range(len(X_test)):
    x = X_test_indices
    num = np.argmax(pred[i])
    if(num != Y_test[i]):
        print('Expected emotion:'+ label_to_emotion(Y_test[i]) + ' prediction: '+ X_test[i] + label_to_emotion(num).strip())

['i', 'feel', 'so', 'enraged', 'but', 'helpless', 'at', 'the', 'same', 'time']
['i', 'like', 'super', 'committed', 'like', 'to', 'the', 'point', 'where', 'i', 'feel', 'like', 'i', 'could', 'honestly', 'see', 'myself', 'marrying', 'the', 'person', 'and', 'am', 'not', 'a', 'fan', 'of', 'casual', 'sex', 'or', 'sex', 'without', '5', 'or', 'any', 'of', 'that', 'does', 'your', 'mate', 'need', 'to', 'be', 'taller', 'than', 'you']
['i', 'feel', 'strange', 'or', 'will', 'i', 'ever', 'notice', 'that']
['i', 'could', 'feel', 'the', 'poisoned', 'hateful', 'angry', 'buildup', 'leaving', 'and', 'it', 'made', 'me', 'feel', 'lighter']
['i', 'was', 'feeling', 'so', 'distressed', 'so', 'it', 'has', 'been', 'added', 'to', 'my', 'notes', 'that', 'i', 'should', 'never', 'be', 'prescribed', 'them', 'again']
['i', 'feel', 'you', 'as', 'my', 'best', 'man', 'someone', 'who', 'moves', 'me', 'touches', 'my', 'soul', 'and', 'puts', 'fire', 'in', 'my', 'body']
['i', 'feel', 'as', 'though', 'im', 'carefree']
['i', 

In [30]:
# Predictions-available in x_test.  
x_test = np.array(['i want to get out there and feel as amazing as i once did on a run'])
X_test_indices = sentences_to_indices(x_test, word_to_index, maxLen)
print(x_test[0] +' '+  label_to_emotion(np.argmax(model.predict(X_test_indices))))

['i', 'want', 'to', 'get', 'out', 'there', 'and', 'feel', 'as', 'amazing', 'as', 'i', 'once', 'did', 'on', 'a', 'run']
i want to get out there and feel as amazing as i once did on a run :surprise:


In [31]:
  
x_test = np.array(['i am loved by my action'])
X_test_indices = sentences_to_indices(x_test, word_to_index, maxLen)
print(x_test[0] +' '+  label_to_emotion(np.argmax(model.predict(X_test_indices))))

['i', 'am', 'loved', 'by', 'my', 'action']
i am loved by my action :joy:


In [34]:
# New untrained Text
x_test = np.array(['I have a painful feeling'])
X_test_indices = sentences_to_indices(x_test, word_to_index, maxLen)
print(x_test[0] +' '+  label_to_emotion(np.argmax(model.predict(X_test_indices))))

['i', 'have', 'a', 'painful', 'feeling']
I have a painful feeling :sadness:
